version: "3.7"
networks:
  backend:
  banco:
services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - backend
      - banco
    depends_on:
      - banco
    environment:
      PORT: '3000'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: banco
  banco:
    container_name: banco
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
    networks:
      - banco
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'XP-invest'